import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'
import { createVuetify } from 'vuetify'

// Import only the components you need to reduce bundle size
import {
  VApp,
  VMain,
  VBtn,
  VCard,
  VCardText,
  VCardTitle,
  VSelect,
  VTextField,
  VTabs,
  VTab,
  VTabsWindow,
  VTabsWindowItem,
  VIcon,
  VContainer,
  VRow,
  VCol,
  VChip,
  VProgressLinear,
  VProgressCircular,
  VDialog,
  VDivider,
  VList,
  VListItem,
  VListItemTitle,
  VMenu,
  VSheet,
  VToolbar,
  VToolbarTitle,
  VNavigationDrawer,
  VAppBar,
  VSwitch,
  VCheckbox,
  VRadio,
  VRadioGroup,
  VTextarea,
} from 'vuetify/components'

import { Ripple } from 'vuetify/directives'

export default createVuetify({
  components: {
    VApp,
    VMain,
    VBtn,
    VCard,
    VCardText,
    VCardTitle,
    VSelect,
    VTextField,
    VTabs,
    VTab,
    VTabsWindow,
    VTabsWindowItem,
    VIcon,
    VContainer,
    VRow,
    VCol,
    VChip,
    VProgressLinear,
    VProgressCircular,
    VDialog,
    VDivider,
    VList,
    VListItem,
    VListItemTitle,
    VMenu,
    VSheet,
    VToolbar,
    VToolbarTitle,
    VNavigationDrawer,
    VAppBar,
    VSwitch,
    VCheckbox,
    VRadio,
    VRadioGroup,
    VTextarea,
  },
  directives: {
    Ripple,
  },
  theme: {
    defaultTheme: 'dark',
    themes: {
      dark: {
        colors: {
          primary: '#6366f1',
          secondary: '#8b5cf6',
          accent: '#06b6d4',
          error: '#ef4444',
          warning: '#f59e0b',
          info: '#3b82f6',
          success: '#10b981',
        },
      },
    },
  },
})